server:
  port: 8082

spring:
  application:
    name: ms-inventory
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/inventory_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: KEBAB_CASE

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] [%X{requestId}] %-40.40logger{39} : %m%n"

products:
  base-url: ${PRODUCTS_BASE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

application:
  security:
    api-key: inventory-microservices-api-key-12345
